name: forty-eight-hour-cleanup

on:
  - push
  # schedule:
  #   - cron: 0 0 1/2 * *

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.CLEANUP_ACTION}}
      - run: |
          git checkout master
          git branch -r
          echo ${GITHUB_CONTEXT}