name: Shell Commands

on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World!"
      - name: Echo multiple strings
        run: |
          echo ${{node -v}}
          npm -v
      - name: Python Command
        shell: python
        run: |
          import platform
          print (platform.processor())