name: Checkout Repository

on: 
  create

jobs:
  clone-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}
      - run: |
          pwd
          ls -a
          git branch -a
          echo $GITHUB_REF
          git push origin -d test5
          git branch -a