name: Checkout Repository

on: push

jobs:
  clone-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}
      - run: |
          pwd
          ls -a
          git branch -a
          git push origin -d test3
          git branch -a