name: Delete Branch

on: 
  - create

jobs:
  clone-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTION_TOKEN }}
      - run: |
          git checkout master
          git push origin -d $GITHUB_REF