name: branch-name-alert

on:
  - push
  - create

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
    # if: ${GITHUB_REF}=='DASRE-/'
    container: 
      image: node:20-alpine3.16
    steps:
      # - name: send a slack Message
      #   uses: docker://technosophos/slack-notify
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SOUMYADEEPSP_SLACK_WEBHOOK }}
      #     SLACK_MESSAGE: "Hello this is your slack bot"
      - name: echo
        run: echo ${GITHUB_CONTEXT.triggering_actor}