name: Send Slack Message

on:
  - push
  - create

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container: 
      image: node:20-alpine3.16
    steps:
      - name: send a slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SOUMYADEEPSP_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello this is your slack bot"