name: Branch-name-alert

on:
  - create

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    env: 
      GITHUB_CONTEXT: ${{ toJson(github) }}
    # if: github.ref_name=='DASRE-*'
    if: startsWith(github.ref_name, 'DASRE') || startsWith(github.ref_name, 'test')
    container: 
      image: node:20-alpine3.16
    steps:
      - name: send a slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SOUMYADEEPSP_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello this is your slack bot"